image: fedora/latest
packages:
  - tar
environment:
  goversion: 1.23.4
  reponame: stravautil
sources:
    - https://git.sr.ht/~ernie/stravautil
tasks:
    - setup-mongo: |
        sudo dnf install -y 'dnf5-command(config-manager)'
        sudo dnf config-manager addrepo --set=baseurl=https://repo.mongodb.org/yum/amazon/2023/mongodb-org/8.0/x86_64
        curl -LO https://www.mongodb.org/static/pgp/server-8.0.asc
        sudo rpm --import server-8.0.asc
        sudo dnf install -y mongodb-org
        sudo systemctl start mongod
        sudo dnf swap mongodb-mongosh  mongodb-mongosh-shared-openssl3 -y
    - setup-golang: |
        curl -LO https://golang.org/dl/go${goversion}.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf go${goversion}.linux-amd64.tar.gz
        sudo ln -s /usr/local/go/bin/* /usr/local/bin/
    - build: |
        cd ${reponame}
        go build
    - vet: |
        cd ${reponame}
        go vet
    - test: |
        cd ${reponame}
        # ./scripts/setup_empty_db.sh
        go test -v
triggers:
  - action: email
    condition: always
    to: Ernie Hershey <builds.sr.ht@ernie.org>
